version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1  # Для вывода логов в реальном времени
    env_file:
      - .env
    command: ["./start.sh"]
